### ISSUE TITLE
`Killed` if I use FSDPTrainer or TensorParallelTrainer

### ISSUE THREAD

**Issue by zabir-nabil** [eric-mitchell/direct-preference-optimization#11]
Thanks for releasing the codebase.
I ran the code for Pythia28 with BasicTrainer, it seems to be running fine. But if I try the other trainers I get `killed` signal (I am using 4 A100 GPUs in `slurm`, so should not be a memory issue). Do you have any idea what may be the reason? 🤔

With BasicTrainer only GPU 0 is used, no other GPU is being used 😕

**Comment by zabir-nabil** [comment]
The nan issue is due to `dtype`, I changed to float16 to bfloat16 and it seems to work.

**Comment by eric-mitchell** [comment]
I'd guess an insufficient RAM issue. How much memory are you requesting on your slurm job (with --mem)?

**Comment by zabir-nabil** [comment]
Thanks for prompt reply. I think there should be enough ram, how much ram is needed usually to run the experiments?
 total        used        free      shared  buff/cache   available
Mem:           2.0T         26G        1.7T        1.2G        292G        1.9T
Swap:           15G          0B         15G

**Comment by eric-mitchell** [comment]
Are you launching with sbatch/srun? The issue is not the amount of RAM free on the machine, it's the amount of RAM your slurm job actually requests (which can be considerably lower).

**Comment by zabir-nabil** [comment]
Thanks a lot, makes sense, I didn't request ram memory explicitly. Let me try that.
The other thing, does the basictrainer supposed to use a single GPU always even if multiple gpus are available? I can only fit batch 2 with 1 A100.

**Comment by eric-mitchell** [comment]
The basictrainer should split the model across all available GPUs by default: https://github.com/eric-mitchell/direct-preference-optimization/blob/main/train.py#L76.
