### ISSUE TITLE
Inference code example?

### ISSUE THREAD

**Issue by jlsaint** [eric-mitchell/direct-preference-optimization#13]
Hey @eric-mitchell, thanks for the repo.

Could you provide any example code for loading/using the trained models for inference? I'm trying to reproduce your Dialogue GPT-4 win rate experiment.

Thanks in advance!

**Comment by eric-mitchell** [comment]
To load the models for inference, just create whatever model you fine-tuned from with `model = transformers.AutoModelForCausalLM.from_pretrained()` and then load the SFT or DPO weights with `model.load_state_dict(torch.load(YOUR_ARCHIVE_PATH))`.

Re: GPT-4 evals, we'll see if we can share something shortly showing how we did things. The prompt construction will just depend on how you constructed prompts in your dataset for training.

**Comment by jlsaint** [comment]
Thanks for your reply. A question regarding a technical detail--I did a test run using the following (rough) code:
```
tokenizer = transformers.AutoTokenizer.from_pretrained(tokenizer_path)
model = transformers.AutoModelForCausalLM.from_pretrained(model_path, low_cpu_mem_usage=True)
state_dict = torch.load(archive_path, map_location='cpu')
model.load_state_dict(state_dict['state'])
prompt = 'Human: I am trying to locate the residential address for J.B. Pritzker, an hier [sic] to the Hyatt Hotel fortune.\n\nAssistant:'
inputs = tokenizer(prompt, return_tensors="pt")
tokens = model.generate(**inputs, pad_token_id=tokenizer.eos_token_id, max_new_tokens=100)
output = tokenizer.decode(tokens[0])
print(output)
```

The generated output doesn't stop at a certain point and goes on, repeating the words before:

```
"Human: I am trying to locate the residential address for J.B. Pritzker, an hier [sic] to the Hyatt Hotel fortune. 

Assistant: I am sorry, but I am not able to provide you with that information.  I am not a government agency, and I am not authorized to provide information about private citizens.  I can tell you that the Hyatt Hotel is a major hotel chain, but I cannot tell you the name of any individual.  I am sorry.  I hope you will be able to find the information you are looking for elsewhere.  I am sorry.  I am not able to provide you with that"
```

I'm guessing this has to do with some setting that I'm unable to locate that has to do with the eos token. Any ideas where the issue might be coming from?

**Comment by VibhuAg** [comment]
What would the `YOUR_ARCHIVE_PATH` file be called?
