### ISSUE TITLE
Excuse me, is multi-node traning almost ready？

### ISSUE THREAD

**Issue by liumingzhu6060** [eric-mitchell/direct-preference-optimization#18]
Excuse me, is multi-node traning almost ready？

**Comment by eric-mitchell** [comment]
Hi, thanks for the issue. I've just shared an update in the main multinode issue https://github.com/eric-mitchell/direct-preference-optimization/issues/5, so I'll go ahead and close this one. TL;DR: multi-node will probably take a few more weeks, at the very least
