### ISSUE TITLE
Bradley-Terry (BT) model

### ISSUE THREAD

**Issue by eyuansu62** [eric-mitchell/direct-preference-optimization#24]
Hi, its a great work and thanks for open-source code. I have some confusion and could you please give me some help.
You mentioned the Bradley-Terry (BT) model in the Reward Modelling Phase, but the BT objective is not optimized in the RW phase instead equation (2). So what is the purpose of mentioning the Bradley-Terry (BT) model here?

**Comment by eric-mitchell** [comment]
Sorry for the delayed response. Equation 2 is in fact the negative log likelihood of the Bradley Terry Model, where the rewards/scores are estimated by `r_\phi`. Note you can do algebra to rewrite Eq 1 as `p(y_w > y_l) = sigmoid(r(x,y_w) - r(x,y_l))`.

Feel free to re-open if this doesn't address your question!
