### ISSUE TITLE
Request to Cite Our ICML2023 Poster Paper in DPO

### ISSUE THREAD

**Issue by yachenkang** [eric-mitchell/direct-preference-optimization#25]
A very interesting piece of work! 

We would like to kindly request that you consider adding our paper titled *[Beyond Reward: Offline Preference-guided Policy Optimization](https://openreview.net/forum?id=0BgDXE6vJJ)*, which has been officially published at ICML2023 as poster paper, to the references of the subsequent modified version of DPO. 

We believe that the two works share similar problem settings, as both attempt to remove the reinforcement learning process in the RLHF framework. Although the implementation methods of the two papers are not exactly the same, we still believe that citing our paper will make DPO more rigorous, especially considering that this is still a developing field. 

We hope you will seriously consider our request.

```markdown
@article{kang2023beyond,
  title={Beyond reward: Offline preference-guided policy optimization},
  author={Kang, Yachen and Shi, Diyuan and Liu, Jinxin and He, Li and Wang, Donglin},
  journal={arXiv preprint arXiv:2305.16217},
  year={2023}
}
```

**Comment by eric-mitchell** [comment]
Thanks for bringing your paper to our attention- we will certainly discuss it in our next revision of the DPO paper! Nice work.

Feel free to drop us an email (corresponding authors contact info is in the DPO paper) if you'd like to discuss further!

**Comment by yachenkang** [comment]
The DPO has been published and has had a significant impact in the field. Congratulations to your team!
However, I have carefully read the latest version of the paper and it seems that there is no reference to OPPO. I would like to know if this omission is due to my oversight while reading?
