### ISSUE TITLE
IMDB experiments preference pair generation

### ISSUE THREAD

**Issue by abhimasand** [eric-mitchell/direct-preference-optimization#28]
In the controlled sentiment generation part, it is mentioned that you generate preference pairs over generation with a pre-trained sentiment classifier. I see an earlier issue earlier where the sentiment classifier is mentioned, however, what model is actually used to perform the text completion for generating the preference pairs? 

Thank you very much in advance!

**Comment by eric-mitchell** [comment]
This is a fine-tuned GPT-2-large model; you can find the weights [here](https://drive.google.com/file/d/1ZPlfmfkCindqJfD8eNrl8kwtMJ2f1Nqv/view?usp=sharing).
