### ISSUE TITLE
Convert PyTorch Model to Hugging Face model

### ISSUE THREAD

**Issue by liumingzhu6060** [eric-mitchell/direct-preference-optimization#3]
DPO model is .pt, how can I convert to Hugging Face model, thanks.

**Comment by eric-mitchell** [comment]
The easiest way is probably just to load whatever model you started with, load the `.pt`, and then save the updated model with `.save_pretrained`. For example:

```
model = transformers.AutoModelForCausalLM.from_pretrained('gpt2-xl')
model.load_state_dict(torch.load('/path/to/your/dpo/checkpoint.pt')['state'])
model.save_pretrained('/some/path/to/save/to')
```

Will close this issue, but feel free to re-open if this doesn't solve your problem.
