### ISSUE TITLE
Request for PPO code

### ISSUE THREAD

**Issue by haikangdeng** [eric-mitchell/direct-preference-optimization#31]
In the paper, you include two PPO-GT methods for comparison, one from trlx and one implemented by yourself. Do you mind adding your implementation of PPO-GT to the repo? 

Thanks in advance.

**Comment by eric-mitchell** [comment]
We're working on cleaning that up now, but we're quite a bit backlogged and so won't get to it immediately. I believe the main change we made to the TRL PPO implementation used in the TRL PPO sentiment example was just increasing the number of samples drawn per prompt. You can refer also to https://github.com/eric-mitchell/direct-preference-optimization/issues/27.

When we are able to include our PPO implementation, I will update here. Sorry for the inconvenience!

**Comment by haikangdeng** [comment]
I see, thanks
