### ISSUE TITLE
question about dpo rewards, why does the reward not start from 0?

### ISSUE THREAD

**Issue by delingha** [eric-mitchell/direct-preference-optimization#34]
hello, thanks for your great work.

I've noticed in the wandb log you provided that the reward value (chosen/reject/margins) starts from a value close to 0 at step 0. According to the code, shouldn't it be 0 here? In other words, the reference model and policy model are supposed to be identical at the beginning.
![image](https://github.com/eric-mitchell/direct-preference-optimization/assets/53307707/0b16ab4e-7c1a-4113-b09d-8098bcf546f2)
https://github.com/eric-mitchell/direct-preference-optimization/blob/main/trainers.py#L75-L76
Looking forward to your reply :)

**Comment by ppq12138** [comment]
In my understanding, during training, the model is in the "train" state, and modules such as drop out can cause different outputs for the same input.

**Comment by delingha** [comment]
> In my understanding, during training, the model is in the "train" state, and modules such as drop out can cause different outputs for the same input.

I noticed that dropout is turned off at https://github.com/eric-mitchell/direct-preference-optimization/blob/main/train.py#L85-L92 here. It probably isn't the cause for this. 
Furthermore, the evaluation takes place during the initial stages of training, specifically at step 0, where ’training ‘ operations shouldn't have occurred yet.

**Comment by eric-mitchell** [comment]
Good observation- dropout is indeed turned off. However we put the reference model in fp16 because we're only using it for inference, while the policy stays in fp32 for training. fp16 introduces some very small approximation error, which is why the reward margins don't start at exactly zero.
