### ISSUE TITLE
Can we remove reference model during training?

### ISSUE THREAD

**Issue by LuJunru** [eric-mitchell/direct-preference-optimization#37]
Is it possible to compute reference_chosen_logps and reference_rejected_logps offline? Since the reference model is frozen, I think we don't need to load it on-fly, so that we can leave all memories to policy model.

**Comment by LuJunru** [comment]
By the way, ```float32``` dtype used here may cause memory overflow: https://github.com/eric-mitchell/direct-preference-optimization/blob/main/trainers.py#L207.

**Comment by eric-mitchell** [comment]
Yes, we can- see this issue: https://github.com/eric-mitchell/direct-preference-optimization/issues/29

PRs for supporting this feature are welcome!

However the conversion to fp32 at that line is needed so the softmax in _get_batch_logps can be done in fp32 not fp16.
