### ISSUE TITLE
Loss is 0 when policy and reference models are the same

### ISSUE THREAD

**Issue by luffycodes** [eric-mitchell/direct-preference-optimization#46]
Hi,

I had a question about the implementation. When the policy and reference models are the same, will the loss not be 0?
https://github.com/eric-mitchell/direct-preference-optimization/blob/main/trainers.py#L72
Or equation 7 in the paper?

Maybe I am missing something? Can you please help me understand it better?

**Comment by nomadlx** [comment]
I have the same confusion, I see you closed the question, any suggestions to help me understand this?

**Comment by luffycodes** [comment]
in the first iteration i guess loss might be 0 if dropout is not 0.. then in later iterations since only the policy model is getting updated through dpo loss (reference model is not updated), the loss objective makes sure that the policy model does not deviate too much from the original weights (stored in reference model).

**Comment by magneto0124** [comment]
> I have the same confusion, I see you closed the question, any suggestions to help me understand this?

#4 
The loss plot in this issue shows that when policy model and reference model have same output, it will result in x = 0 and loss will be like 0.693147 rather than 0.
