### ISSUE TITLE
Appendix A.4 of the papper: the derived gradient is not consistent with the main text

### ISSUE THREAD

**Issue by yflyzhang** [eric-mitchell/direct-preference-optimization#63]
Thank you very much for making the code public!

But in the paper (https://arxiv.org/pdf/2305.18290.pdf), page 17, the derived gradient of DPO is not consistent with the main text.
This is likely to be induced by the fact that $y_w$ and $y_l$ are placed in the wrong places in equation (22),  and so does the final gradient equation.

**Comment by rustic-snob** [comment]
I opened an issue related to this at #60, and it will be updated in next revision.

**Comment by yflyzhang** [comment]
> I opened an issue related to this at #60, and it will be updated in next revision.

Thank you for pointing this out. I even forgot to check the closed issues first.
