### ISSUE TITLE
question about chosen rewards and rejected rewards?

### ISSUE THREAD

**Issue by platoonpluto** [eric-mitchell/direct-preference-optimization#8]
@eric-mitchell  according to your [dpo demo charts ](https://wandb.ai/eric_anthony_mitchell/dpo-demos/runs/xclpzupm/workspace?workspace=user-), train_chosen_rewards and train_rejected_rewards are all NEGATIVE values, which means model learns to assign a lower log probability relative to ref model. is this means model degenerate?

![企业微信截图_16883482646533](https://github.com/eric-mitchell/direct-preference-optimization/assets/11864324/506f01e4-180a-49c1-9c9e-4863c9a450b4)

![企业微信截图_16883482814108](https://github.com/eric-mitchell/direct-preference-optimization/assets/11864324/ec184eec-5c23-4771-8701-0a4507faf4cb)

BTW. I reimplemented DPO algorithm and got almost identical chosen/rejected reward curve, but model generate duplicate tokens always.

Afterwards, I change the objective function to log(sigmoid(chosen_log_prob)), which makes the model learns in a supervised finetuning manner, and then chosen reward values are all POSITIVE values.

**Comment by eric-mitchell** [comment]
Negative rewards are definitely not a sign that the model is degenerate; the wandb output you linked includes samples from the policy in the "Tables" section, and they seem very reasonable (if not always correct). The absolute magnitude of the chosen/rejected rewards isn't actually important; what matters is that the chosen rewards are higher than the rejected rewards (the model assigns higher reward to the chosen responses than the rejected ones).

I can't tell you what might be going wrong with your implementation with the information you've given, but I'd guess there is a bug in your implementation if you're getting degenerate outputs. I'll close this issue for now, but feel free to re-open if you have any lingering questions.
